import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AuthProvider from "./providers/SessionProvider";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import NextAuthSessionProvider from "./providers/NextAuthSessionProvider";
import ReduxProvider from "./providers/ReduxProvider";
import Toast from "./constants/toastify";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
}
